jobs:
- job: library
  displayName: Build Library 🦄
  pool:
    vmImage: 'macOS-10.13'

  strategy:
    maxParallel: 10
    matrix:
      node-10:
        node_version: ^10.6.0

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js 🐍'

  - script:  npm ci
    displayName: 'Install dependencies 📦'

  - script: yarn bootstrap
    displayName: 'Lerna bootstrap 🥾'

  - script: yarn lint
    displayName: 'Run linting'

#   - script: |
#       yarn build
#     displayName: 'Build applications'

#   - script: |
#       yarn test
#     displayName: 'Run testing'


#   steps:
#   - script: docker build  .
#     displayName: 'Create Docker image'



- job: Docker
  displayName: Docker 🐳
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - script: |
        docker build -t sketchmine/sketch-validator . \
          -f ./packages/sketch-validator-nodejs-wrapper/Dockerfile
      displayName: 'Build Docker images 🐳 '

    - script: |
        docker login -u $(docker-hub-user) -p $(docker-hub-password)
        docker push sketchmine/sketch-validator
      displayName: 'Publish Docker images 🐳 🚀'
      # condition: and(succeeded())
#     condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))


variables:
- group: docker-hub-credentials
