# docker-compose.yml
version: '3.4'

services:
  library:
    build: 
      target: library-production
      context: .
      args:
        GIT_TAG: 7.1.1
    cap_add:
      - ALL
    volumes:
      - ./src:/src
      - ./config:/config
    environment:
      DEBUG: 'true'
      # DEBUG: 'puppeteer:*' # puppeteer logging in browser
      DOCKER: 'true'
    command: ['node', './dist/library']

volumes:
  src:
  config: